sample_file: "samples_info.tab"
genome: "/gpfs/data/fisherlab/genomes/mm10/bowtie2/mm10_index"
spike_genome: "/gpfs/data/fisherlab/genomes/ec_K12_MG1655/Escherichia_coli_K_12_MG1655/NCBI/2001-10-15/Sequence/Bowtie2Index/genome"
GTF: "/gpfs/data/fisherlab/genomes/mm10/gencode.vM25.annotation.gtf"